# Generated by Django 3.1.7 on 2021-03-10 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=100)),
                ('movie_category', models.CharField(max_length=100)),
                ('movie_duration', models.CharField(max_length=100)),
                ('movie_country', models.CharField(max_length=100)),
                ('producer_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('movie_image', models.ImageField(upload_to='')),
            ],
        ),
    ]
