# Generated by Django 3.1.7 on 2021-03-10 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20210310_1909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='created_on',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
