# Generated by Django 3.1.7 on 2021-03-11 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20210311_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='created_on',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='last_modified',
            field=models.DateTimeField(),
        ),
    ]
