# Generated by Django 3.1.7 on 2021-03-11 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20210311_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
