# Generated by Django 3.1.7 on 2021-03-11 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20210311_1339'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='movie_category',
            new_name='categories',
        ),
    ]
